- name: Frontend Configuration
  hosts: webservers
  become: yes

  vars:
      required_ram_mb: 1024

 tasks:
    - name: Install NGINX only if Ubuntu
      apt:
        name: nginx
        state: present
        update_cache: yes
        when: ansible_facts['os_family'] == "Debian"

    - name: Ensure NGINX is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
       - vim
       - git
       - curl

    - name: Check available memory
      debug:
        msg: "Available memory: {{ ansible_facts.memtotal_mb }} MB"

    - name: Create a simple HTML page
      copy:
        content: "<h1>Oii I am Malak Wagieh!</h1>"
        dest: /var/www/html/index.nginx-debian.html
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
